"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { getBulkSendConfirmationTier } from "@email-platform/types";
import { Card, CardBody } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input, Label, Select, Textarea } from "@/components/ui/input";
import { useToast } from "@/components/ui/toast";
import { useConfirm } from "@/components/ui/confirm-dialog";
import { getErrorMessage } from "@/hooks/use-api-error";
import { useTemplates, usePreviewTemplate, useSendTestEmail } from "@/hooks/use-templates";
import { useRecipientLists, useImportPreview, useConfirmImport } from "@/hooks/use-recipients";
import { useSignatures } from "@/hooks/use-signatures";
import { useCreateCampaign, useSendCampaign, generateIdempotencyKey } from "@/hooks/use-campaigns";
import { useComposeStore } from "@/store/compose-store";
import { WizardStepper, WIZARD_STEPS } from "@/components/compose/wizard-shell";
import { BlockPreview } from "@/components/templates/block-preview";

const validEmail = (value: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);

export default function ComposePage() {
  const router = useRouter(), params = useSearchParams(), store = useComposeStore();
  const { toast } = useToast(); const confirm = useConfirm();
  const { data: templates } = useTemplates(undefined, "ACTIVE"); const { data: lists } = useRecipientLists(); const { data: signatures } = useSignatures();
  const previewMutation = usePreviewTemplate(store.templateId || "__none__"); const testMutation = useSendTestEmail(store.templateId || "__none__");
  const importPreview = useImportPreview(), confirmImport = useConfirmImport(), createCampaign = useCreateCampaign();
  const [campaignId, setCampaignId] = useState<string | null>(null), sendCampaign = useSendCampaign(campaignId || "__none__");
  const [emailsText, setEmailsText] = useState(""), [csvFile, setCsvFile] = useState<File | null>(null), [preview, setPreview] = useState<string | null>(null);
  const [count, setCount] = useState(0), [typedCount, setTypedCount] = useState(""), [idempotencyKey] = useState(generateIdempotencyKey);
  useEffect(() => { const id = params.get("templateId"); if (id && id !== store.templateId) store.setTemplateId(id); }, [params, store]);
  const template = templates?.find((item) => item.id === store.templateId);
  const emails = useMemo(() => emailsText.split(/[\n,]/).map((item) => item.trim()).filter(Boolean), [emailsText]);
  const invalidEmails = emails.filter((email) => !validEmail(email));
  const recipientReady = store.recipientSource === "manual" ? emails.length > 0 && invalidEmails.length === 0 : store.recipientSource === "list" ? !!store.recipientListId : !!store.csvFileAssetId;

  function next() { if (!recipientReady) return toast({ title: invalidEmails.length ? "Fix invalid email addresses" : "Add recipients first", variant: "error" }); store.setStep(Math.min(store.step + 1, 2)); }
  async function analyzeCsv() { if (!csvFile) return; try { const result = await importPreview.mutateAsync(csvFile); store.setCsvFileAssetId(result.fileAssetId); toast({ title: "CSV ready", description: `${result.validEmails} valid recipients found.`, variant: "success" }); } catch (error) { toast({ title: "CSV upload failed", description: getErrorMessage(error), variant: "error" }); } }
  async function loadPreview() { try { setPreview((await previewMutation.mutateAsync(store.variableMapping)).html); } catch (error) { toast({ title: "Preview failed", description: getErrorMessage(error), variant: "error" }); } }
  async function testEmail() { if (!validEmail(store.testEmail)) return toast({ title: "Enter a valid test email", variant: "error" }); try { await testMutation.mutateAsync({ toEmail: store.testEmail, sampleVariables: store.variableMapping }); toast({ title: "Test email sent", variant: "success" }); } catch (error) { toast({ title: "Test email failed", description: getErrorMessage(error), variant: "error" }); } }
  async function prepare() {
    if (!template) return;
    let recipientListId = store.recipientSource === "list" ? store.recipientListId : undefined;
    if (store.recipientSource === "csv" && store.csvFileAssetId) try { recipientListId = (await confirmImport.mutateAsync({ fileAssetId: store.csvFileAssetId, columnMappings: [{ csvHeader: "email", mappedTo: "email" }], newListName: `Email recipients ${new Date().toISOString().slice(0, 10)}` })).listId; } catch (error) { toast({ title: "Recipient import failed", description: getErrorMessage(error), variant: "error" }); return; }
    try { const campaign = await createCampaign.mutateAsync({ name: store.campaignName.trim() || `${template.name} — ${new Date().toLocaleDateString()}`, templateId: template.id, recipientListId, manualRecipientEmails: store.recipientSource === "manual" ? emails : undefined, signatureId: store.signatureId || undefined, customVariableOverrides: store.variableMapping }); setCampaignId(campaign.id); setCount(campaign.totalRecipients); } catch (error) { toast({ title: "Could not prepare email", description: getErrorMessage(error), variant: "error" }); }
  }
  async function send() { if (!campaignId) return; const tier = getBulkSendConfirmationTier(count); if (tier === "explicit" && typedCount !== String(count)) return toast({ title: "Type the exact recipient count to confirm", variant: "error" }); if (tier !== "explicit" && !await confirm({ title: `Send to ${count} recipient${count === 1 ? "" : "s"}?`, description: "This queues the email for immediate sending.", confirmLabel: "Send email", destructive: tier === "enhanced" })) return; try { await sendCampaign.mutateAsync({ idempotencyKey, confirmedRecipientCount: count }); toast({ title: "Email is sending", variant: "success" }); store.reset(); router.push(`/campaigns/${campaignId}`); } catch (error) { toast({ title: "Email could not be sent", description: getErrorMessage(error), variant: "error" }); } }

  return <div className="max-w-4xl space-y-6"><div><h1 className="text-xl font-semibold text-ink-900">Send email</h1><p className="mt-1 text-sm text-ink-500">{template ? `Using ${template.name}` : "Choose a template, add recipients, preview, then send."}</p></div><WizardStepper currentStep={store.step} /><Card><CardBody className="space-y-5">
    {!template ? <TemplatePicker templates={templates} select={store.setTemplateId} /> : null}
    {template && store.step === 0 ? <Recipients store={store} lists={lists} signatures={signatures} emailsText={emailsText} setEmailsText={setEmailsText} invalidEmails={invalidEmails} csvFile={csvFile} setCsvFile={setCsvFile} analyzeCsv={analyzeCsv} loading={importPreview.isPending} /> : null}
    {template && store.step === 1 ? <div className="space-y-4"><Summary template={template} /><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={loadPreview} loading={previewMutation.isPending}>Refresh preview</Button><Input className="max-w-xs" placeholder="test@company.com" value={store.testEmail} onChange={(event) => store.setTestEmail(event.target.value)} /><Button variant="outline" size="sm" onClick={testEmail} loading={testMutation.isPending}>Send test</Button></div><div className="overflow-hidden rounded-lg border border-ink-100">{preview ? <iframe title="Email preview" srcDoc={preview} className="h-[500px] w-full bg-white" /> : template.currentVersion ? <BlockPreview blocks={template.currentVersion.bodyBlocksJson.blocks} subject={template.currentVersion.subject} variables={store.variableMapping} /> : null}</div></div> : null}
    {template && store.step === 2 ? <div className="space-y-4"><Summary template={template} />{!campaignId ? <Button onClick={prepare} loading={createCampaign.isPending || confirmImport.isPending}>Prepare email</Button> : <div className="space-y-3"><p className="text-sm text-ink-700">Prepared for {count} recipient{count === 1 ? "" : "s"}.</p>{getBulkSendConfirmationTier(count) === "explicit" ? <><Label>Type {count} to confirm</Label><Input value={typedCount} onChange={(event) => setTypedCount(event.target.value)} /></> : null}<Button onClick={send} loading={sendCampaign.isPending}>Send email</Button></div>}</div> : null}
  </CardBody></Card>{template && store.step < 2 ? <div className="flex justify-between"><Button variant="outline" onClick={() => store.step === 0 ? router.push("/templates") : store.setStep(store.step - 1)}>Back</Button><Button onClick={next}>{store.step === 0 ? "Preview email" : "Continue to send"}</Button></div> : null}</div>;
}

function TemplatePicker({ templates, select }: any) { return <div className="space-y-3"><Label required>Choose template</Label><div className="grid gap-2 sm:grid-cols-2">{templates?.map((template: any) => <button key={template.id} onClick={() => select(template.id)} className="rounded-lg border border-ink-200 p-4 text-left hover:bg-ink-50"><p className="font-medium text-ink-900">{template.name}</p><p className="mt-1 text-sm text-ink-500">{template.currentVersion?.subject || "No subject"}</p></button>)}</div></div>; }
function Summary({ template }: any) { return <div className="rounded-lg border border-ink-200 bg-ink-50 p-4"><p className="text-xs font-medium uppercase text-ink-500">Email template</p><p className="mt-1 font-medium text-ink-900">{template.name}</p><p className="text-sm text-ink-600">Subject: {template.currentVersion?.subject}</p></div>; }
function Recipients({ store, lists, signatures, emailsText, setEmailsText, invalidEmails, csvFile, setCsvFile, analyzeCsv, loading }: any) { return <div className="space-y-5"><div><Label required>Recipients</Label><div className="mt-2 flex flex-wrap gap-4">{(["manual", "list", "csv"] as const).map((source) => <label key={source} className="flex items-center gap-2 text-sm"><input type="radio" checked={store.recipientSource === source} onChange={() => store.setRecipientSource(source)} />{source === "manual" ? "Email addresses" : source === "list" ? "Recipient list" : "CSV upload"}</label>)}</div></div>{store.recipientSource === "manual" ? <div><Label>Recipient email addresses</Label><Textarea rows={5} placeholder="jane@example.com, john@example.com" value={emailsText} onChange={(event) => setEmailsText(event.target.value)} />{invalidEmails.length ? <p className="mt-1 text-sm text-red-600">Invalid: {invalidEmails.join(", ")}</p> : <p className="mt-1 text-xs text-ink-500">Separate addresses with commas or new lines.</p>}</div> : null}{store.recipientSource === "list" ? <Select value={store.recipientListId} onChange={(event) => store.setRecipientListId(event.target.value)}><option value="">Select a recipient list</option>{lists?.map((list: any) => <option key={list.id} value={list.id}>{list.name}</option>)}</Select> : null}{store.recipientSource === "csv" ? <div className="space-y-2"><input type="file" accept=".csv,text/csv" onChange={(event) => setCsvFile(event.target.files?.[0] ?? null)} /><Button variant="outline" size="sm" onClick={analyzeCsv} loading={loading} disabled={!csvFile}>Analyze CSV</Button>{store.csvFileAssetId ? <p className="text-sm text-emerald-600">CSV is ready to send.</p> : null}</div> : null}<div className="border-t border-ink-100 pt-5"><Label>Campaign name <span className="font-normal text-ink-400">(optional)</span></Label><Input value={store.campaignName} onChange={(event) => store.setCampaignName(event.target.value)} placeholder="e.g. October product update" /><div className="mt-4"><Label>Signature <span className="font-normal text-ink-400">(optional)</span></Label><Select value={store.signatureId} onChange={(event) => store.setSignatureId(event.target.value)}><option value="">No signature</option>{signatures?.map((signature: any) => <option key={signature.id} value={signature.id}>{signature.name}</option>)}</Select></div><VariableOverrides value={store.variableMapping} onChange={store.setVariableMapping} /></div></div>; }
function VariableOverrides({ value, onChange }: { value: Record<string, string>; onChange: (value: Record<string, string>) => void }) { return <details className="mt-4"><summary className="cursor-pointer text-sm font-medium text-ink-700">Custom variables (optional)</summary><p className="mt-1 text-xs text-ink-500">Values apply to every recipient in this send.</p><div className="mt-2 space-y-2">{Object.entries(value).map(([key, item]) => <div key={key} className="flex gap-2"><Input placeholder="variable name" value={key} onChange={(event) => { const next = { ...value }; delete next[key]; onChange({ ...next, [event.target.value]: item }); }} /><Input placeholder="value" value={item} onChange={(event) => onChange({ ...value, [key]: event.target.value })} /><Button variant="ghost" size="sm" onClick={() => { const next = { ...value }; delete next[key]; onChange(next); }}>Remove</Button></div>)}<Button variant="outline" size="sm" onClick={() => onChange({ ...value, variable: "" })}>Add variable</Button></div></details>; }
